site_name: Z3Wire
site_description: >-
  Z3 bit-vectors with compile-time type safety and explicit overflow.
  For C++20 and above.
repo_url: https://github.com/qobilidop/z3wire
repo_name: qobilidop/z3wire

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - toc.follow

plugins:
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Examples: https://github.com/qobilidop/z3wire/tree/main/examples
  - Usage:
      - Types: usage/types.md
      - Type Conversions: usage/type-conversions.md
      - Operations: usage/operations.md
  - Development:
      - dev/index.md
      - North Star: dev/north_star.md
      - Roadmap: dev/roadmap.md
      - Architecture: dev/architecture.md
      - Setup: dev/setup.md
      - Commands: dev/commands.md
      - Style: dev/style.md
      - Workflow: dev/workflow.md
