load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

genrule(
    name = "status_register_gen",
    srcs = ["status_register.rdl.txtpb"],
    outs = [
        "status_register.h",
        "status_register.proto",
    ],
    cmd = "$(location //z3wire/weave) --input $(location status_register.rdl.txtpb) --output_dir $(RULEDIR)",
    tools = ["//z3wire/weave"],
)

sh_test(
    name = "status_register_golden_test",
    srcs = ["golden_test.sh"],
    data = [
        "status_register.expected.h",
        "status_register.expected.proto",
        ":status_register_gen",
    ],
)

proto_library(
    name = "status_register_proto",
    srcs = [":status_register.proto"],
)

cc_proto_library(
    name = "status_register_cc_proto",
    deps = [":status_register_proto"],
)

cc_library(
    name = "status_register",
    hdrs = [":status_register.h"],
    deps = [
        ":status_register_cc_proto",
        "//z3wire:bool",
        "//z3wire:int",
        "//z3wire:sym_int",
    ],
)

cc_test(
    name = "status_register_test",
    srcs = ["status_register_test.cc"],
    deps = [
        ":status_register",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "status_register_verification",
    srcs = ["status_register_verification.cc"],
    deps = [":status_register"],
)

sh_test(
    name = "status_register_verification_golden_test",
    srcs = ["verification_golden_test.sh"],
    data = [
        "status_register_verification.expected.txt",
        ":status_register_verification",
    ],
)
