load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "safe_adder",
    srcs = ["safe_adder.cc"],
    deps = ["//z3wire:bitvec"],
)

cc_binary(
    name = "alu",
    srcs = ["alu.cc"],
    deps = ["//z3wire:bitvec"],
)

cc_binary(
    name = "bit_manipulation",
    srcs = ["bit_manipulation.cc"],
    deps = ["//z3wire:bitvec"],
)
