load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "alu",
    srcs = ["alu.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "bit_manipulation",
    srcs = ["bit_manipulation.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "packet_gen",
    srcs = ["packet_gen.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "midpoint_overflow",
    srcs = ["midpoint_overflow.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "safe_adder",
    srcs = ["safe_adder.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)
