load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "barrel_shifter",
    srcs = ["barrel_shifter.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "packet_gen",
    srcs = ["packet_gen.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "multiplier",
    srcs = ["multiplier.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "midpoint_overflow",
    srcs = ["midpoint_overflow.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)

cc_binary(
    name = "adder",
    srcs = ["adder.cc"],
    deps = ["//z3wire:sym_bit_vec"],
)
