load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "bitvec",
    hdrs = ["bitvec.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":bool",
        ":int",
        "@z3//:z3_static",
    ],
)

cc_test(
    name = "bitvec_test",
    srcs = ["bitvec_test.cc"],
    deps = [
        ":bitvec",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "bool",
    hdrs = ["bool.h"],
    visibility = ["//visibility:public"],
    deps = ["@z3//:z3_static"],
)

cc_test(
    name = "bool_test",
    srcs = ["bool_test.cc"],
    deps = [
        ":bool",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "int",
    hdrs = ["int.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "int_test",
    srcs = ["int_test.cc"],
    deps = [
        ":int",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "bitfield",
    hdrs = ["bitfield.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":bitvec",
    ],
)

cc_test(
    name = "bitfield_test",
    srcs = ["bitfield_test.cc"],
    deps = [
        ":bitfield",
        "@googletest//:gtest_main",
    ],
)
