name: Bazel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Restore Bazel disk cache
        uses: actions/cache@v5
        with:
          path: .bazel-disk-cache
          key: bazel-${{ runner.os }}-${{ hashFiles('.bazelversion', 'MODULE.bazel.lock', '.bazelrc') }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: Activate CI-specific Bazel config
        run: |
          echo "build --config=ci" > ci.bazelrc
          echo "build:ci --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" >> ci.bazelrc

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: bazel build //...

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: bazel test //...
