name: Bazel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure remote cache
        run: |
          echo "build --config=remote" > ci.bazelrc
          echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" >> ci.bazelrc

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: bazel build //...

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: bazel test //...

      - name: Coverage
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: |
            ./tools/coverage.sh
            cp "$(bazel info output_path)/_coverage/_coverage_report.dat" coverage.lcov

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage.lcov
