name: Bazel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: ./dev.sh bazel build //...

      - name: Test
        run: ./dev.sh bazel test //...

      - name: Coverage
        run: |
          ./dev.sh ./tools/coverage.sh
          ./dev.sh bash -c 'cp "$(bazel info output_path)/_coverage/_coverage_report.dat" /workspace/coverage.lcov'

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage.lcov
