name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format Check
        run: ./dev.sh ./tools/format.sh --check

      - name: Lint Check
        run: ./dev.sh ./tools/lint.sh
