name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format Check
        run: ./dev.sh ./tools/format.sh --check

      - name: Lint Check
        run: ./dev.sh ./tools/lint.sh

      - name: Build
        run: ./dev.sh bazel build //...

      - name: Test
        run: ./dev.sh bazel test //...

      - name: Coverage
        run: ./dev.sh ./tools/coverage.sh
