name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: cmake --build build

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: ctest --test-dir build --output-on-failure
