name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure remote cache
        run: |
          echo "build --config=remote" > ci.bazelrc
          echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}" >> ci.bazelrc

      - name: Format Check
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: ./tools/format.sh --check

      - name: Lint Check
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/z3wire-dev
          push: never
          runCmd: ./tools/lint.sh
